# SPDX-FileCopyrightText: 2026 Samudra Authors
# SPDX-License-Identifier: Apache-2.0
initializer: &backbone
  ch_width: [128, 192, 256, 384]
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  core_block:
    upscale_factor: 2
    norm: instance
    instance_affine: true
processor: *backbone
activation_checkpointing: true
