# SPDX-FileCopyrightText: 2026 Samudra Authors
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=../schemas/EvalConfig.json

debug: false
save_zarr: true
disk_mode: true
num_model_steps_forward: 50
ckpt_path: null
backend: auto

experiment:
  name: perceiver-spatial-grid-1deg-2in-1out-eval
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online
    entity: ocean_emulators
    project: default
    tags: [torch-hpc, om4-1deg, perceiver-spatial-grid, 2in-1out, evaluation]

data: !include data_2in_1out.yaml
model: !include model.yaml
