repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.1
  hooks:
    - id: ruff
      args: ["--fix", "--config", "pyproject.toml"]
      exclude: ^notebooks/
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=250]
    exclude: ^notebooks/
  - id: trailing-whitespace
  - id: check-yaml
# We define our own mypy checker here rather than using https://github.com/pre-commit/mirrors-mypy
# so it can run within our uv environment & access the correct installed libraries. See:
# https://whynothugo.nl/journal/2023/01/12/notes-on-pre-commit/#using-the-system-plugin-language
- repo: local
  hooks:
  - id: mypy
    name: mypy
    language: system
    require_serial: true
    entry: uv run --dev mypy
    types_or: [python, pyi]
    args: ["--config", "pyproject.toml"]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "v2.5.0"
  hooks:
    - id: pyproject-fmt