resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  cloud: lambda
  # 8x NVIDIA A100 GPU
  accelerators: A100:8
  disk_tier: best
#  disk_size: 1_000 # in GiBs

# FIXME: Remember to pass environment variables with `--env` or `--env-file`
# All `null` values must be specified in order for this script to run!
# When flags are not specified, `sky` will check your local environment variables.
env:
  CONFIG: null
  REMOTE_BUCKET: oa-fomo
  DATA_ROOT_PATH: null # data/om4_onedeg_compact/
  OUTPUT_PATH: outputs/

# FIXME: Please pass in secrets with `--secret`
# When flags are not specified, `sky` will check your local environment variables.
secrets:
  WANDB_API_KEY: null
  AWS_ACCESS_KEY_ID: null
  AWS_SECRET_ACCESS_KEY: null

file_mounts:
  /data:
    name: train-data
    source: s3://${REMOTE_BUCKET}/${DATA_ROOT_PATH}
    mode: COPY

  /outputs:
    name: checkpoints-and-outputs
    source: s3://${REMOTE_BUCKET}/${OUTPUT_PATH}
    mode: MOUNT_CACHED

workdir: .

setup: |
  # Ensure `uv` is installed.
  if ! command -v uv & /dev/null; then
    echo "installing uv."
    curl -LsSf https://astral.sh/uv/install.sh | sh
  else
    echo "uv is already installed."
  fi
  # Install dependencies
  uv sync

run: |
  MASTER_ADDR=$(echo "$SKYPILOT_NODE_IPS" | head -n1)
  echo "Starting distributed training, head node: $MASTER_ADDR"

  # Explicit check for torchrun
  if ! command -v torchrun >/dev/null 2>&1; then
      echo "ERROR: torchrun command not found" >&2
      exit 1
  fi

  uv run torchrun \
    --standalone \
    --nnodes=$SKYPILOT_NUM_NODES \
    --nproc_per_node=$SKYPILOT_NUM_GPUS_PER_NODE \
    --master_addr=$MASTER_ADDR \
    --master_port=8008 \
    --node_rank=${SKYPILOT_NODE_RANK} \
    -m ocean_emulators.train ${CONFIG} \
    --experiment.data_root=/data \
    --data=@configs/data/om4_sky_local.yaml \
    --experiment.base_output_dir=/outputs \
    --experiment.wandb.mode=online \
    --samudra.checkpointing=all