# ~
# Entrypoint to run a training job on a single-node, 8x A100 GPU cluster with skypilot.
# ~
#
# To create or re-use a cluster:
# ```
# export WANDB_API_KEY=<my-key>  # Get your key at https://wandb.ai/authorize
# export AWS_ACCESS_KEY_ID=<my-aws-id>
# export AWS_SECRET_ACCESS_KEY=<my-aws-access-key>
# sky launch -c fomo-cluster train.sky.yaml --env-file <my-env>.env --env WANDB_API_KEY --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY
# ```
# As the job progresses, skypilot will provide commands to locally monitor each stage.
#
#
# To get debug traces when running `sky` commands, set this environment variable:
# ```
# export SKYPILOT_DEBUG=true
# ```
resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  cloud: lambda
  # 8x NVIDIA A100 GPU
  accelerators: A100:8
  disk_tier: best
#  disk_size: 1_000 # in GiBs

# FIXME: Remember to pass environment variables with `--env` or `--env-file`
# FIXME: All `null` values must be specified in order for this script to run!
# When flags are not specified, `sky` should check your local environment variables.
envs:
  # Secrets
  # As of v0.9.3, `sky` supports passing in secrets via a dotenv file! So, you can specify these with `--env-file`.
  # To pass in secrets, we recommend setting environment variable and then ONLY passing in the name via `--env`
  WANDB_API_KEY: null  # e.g. `--env WANDB_API_KEY`
  AWS_ACCESS_KEY_ID: null  # e.g. `--env AWS_ACCESS_ID`
  AWS_SECRET_ACCESS_KEY: null  # e.g. --env AWS_SECRET_ACCESS_KEY`

  CONFIG: null
  OUTPUTS_BUCKET: oa-fomo-outputs
  DATA_BUCKET: oa-fomo
  # We assume that data in this directory is named in the same pattern as
  # the $DATA_CONFIG yaml.
  DATA_ROOT_PATH: null # data/om4_onedeg_compact  # NOTE: path cannot end in a slash `/`.
  DATA_CONFIG: configs/data/om4_sky_local.yaml

file_mounts:
  /data:
    source: s3://${DATA_BUCKET}/${DATA_ROOT_PATH}
    mode: COPY

  /outputs:
    source: s3://${OUTPUTS_BUCKET}
    mode: MOUNT_CACHED

workdir: .

setup: |
  # Ensure `uv` is installed.
  if ! command -v uv & /dev/null; then
    echo "installing uv."
    curl -LsSf https://astral.sh/uv/install.sh | sh
  else
    echo "uv is already installed."
  fi
  # Install dependencies
  uv sync

run: |
  MASTER_ADDR=$(echo "$SKYPILOT_NODE_IPS" | head -n1)
  echo "Starting distributed training, head node: $MASTER_ADDR"

  # Explicit check for torchrun
  if ! command -v torchrun >/dev/null 2>&1; then
      echo "ERROR: torchrun command not found" >&2
      exit 1
  fi

  uv run torchrun \
    --standalone \
    --nnodes=$SKYPILOT_NUM_NODES \
    --nproc_per_node=$SKYPILOT_NUM_GPUS_PER_NODE \
    --master_addr=$MASTER_ADDR \
    --master_port=8008 \
    --node_rank=${SKYPILOT_NODE_RANK} \
    -m ocean_emulators.train ${CONFIG} \
    --experiment.data_root=/data \
    --data=@${DATA_CONFIG} \
    --experiment.base_output_dir=/outputs \
    --experiment.wandb.mode=online \
    --samudra.checkpointing=all