# ~
# Entrypoint to run a training job on a single-node, 8x A100 GPU cluster with skypilot.
# ~
#
# First, make sure that all your credentials are set up:
# ```
# sky check -v
# ```
#
# To create or re-use a cluster:
# ```
# export WANDB_API_KEY=<my-key>  # Get your key at https://wandb.ai/authorize
# sky launch -c fomo-cluster train.sky.yaml --env-file <my-env>.env --env WANDB_API_KEY
# ```
# As the job progresses, skypilot will provide commands to locally monitor each stage.
#
#
# To get debug traces when running `sky` commands, set this environment variable:
# ```
# export SKYPILOT_DEBUG=true
# ```
resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  cloud: lambda
  # 8x NVIDIA A100 GPU
  accelerators: A100:8
  disk_tier: best
#  disk_size: 1_000 # in GiBs

# NOTE: Remember to pass environment variables with `--env` or `--env-file`
# NOTE: All `null` values must be specified in order for this script to run!
envs:
  # Secrets
  # As of v0.9.3, `sky` supports passing in secrets via a dotenv file! So, you can specify these with `--env-file`.
  # To pass in secrets, we recommend setting environment variable and then ONLY passing in the name via `--env`
  WANDB_API_KEY: null  # e.g. `--env WANDB_API_KEY`
  # Run `sky check aws -v` to verify that AWS storage is properly set up.
  # If you still hit permission issues, consider making a dedicated SkyPilot IAM via these docs:
  # https://docs.skypilot.co/en/latest/cloud-setup/cloud-permissions/aws.html#dedicated-skypilot-iam-user

  # TODO(alxmrs): Drive everything except secrets from the primary config file.
  CONFIG: null
  OUTPUTS_BUCKET: oa-fomo-outputs
  DATA_BUCKET: oa-fomo
  # We assume that data in this directory is named in the same pattern as
  # the $DATA_CONFIG yaml.
  DATA_ROOT_PATH: null # data/om4_onedeg_compact  # NOTE: path cannot end in a slash `/`.
  DATA_CONFIG: configs/data/om4_sky_local.yaml

file_mounts:
  /data:
    source: s3://${DATA_BUCKET}/${DATA_ROOT_PATH}
    mode: COPY

  /outputs:
    source: s3://${OUTPUTS_BUCKET}
    mode: MOUNT_CACHED

workdir: .

run: |
  MASTER_ADDR=$(echo "$SKYPILOT_NODE_IPS" | head -n1)
  echo "Starting distributed training, head node: $MASTER_ADDR"

  # Explicit check for torchrun
  if ! command -v torchrun >/dev/null 2>&1; then
      echo "ERROR: torchrun command not found" >&2
      exit 1
  fi

  uv run torchrun \
    --standalone \
    --nnodes=$SKYPILOT_NUM_NODES \
    --nproc_per_node=$SKYPILOT_NUM_GPUS_PER_NODE \
    --master_addr=$MASTER_ADDR \
    --master_port=8008 \
    --node_rank=${SKYPILOT_NODE_RANK} \
    -m ocean_emulators.train ${CONFIG} \
    --data=@${DATA_CONFIG} \
    --experiment.data_root=/data/ \
    --experiment.base_output_dir=/outputs/  \
    --experiment.wandb.mode=online \
    --samudra.checkpointing=all