# yaml-language-server: $schema=../schemas/FOMiniConfig.json

pred_residuals: false
last_kernel_size: 3
pad: "circular"
checkpointing: "all"
perceiver_implementation: "naive"
embedding_dim: 1024
queries_dim: 1024
coordinate_embedding_dim: 512
query_chunk_size: 4096

perceiver:
  depth: 4
  latent_dim: 2304
  num_latents: 512
