defaults:
  - /exp/modules/blocks@core_block: conv_next_block
  - /exp/modules/blocks@up_sampling_block: bilinear_upsample
  - /exp/modules/activations@activation: capped_gelu
  - /exp/modules/blocks@block: swin_blockv2
  - /exp/modules/blocks@downsample_layer: patch_mergev2

_target_: models.swin.SwinTransformer
_recursive_: false
dilation:
  - 1
  - 2
  - 4
  - 8
n_layers:
  - 1
  - 1
  - 1
  - 1
patch_size: 
  - 2
  - 2
window_size:
  - 8
  - 8
embed_dim: 216
depths:
  - 2
  - 2
  - 6
  - 2
num_heads:
  - 3
  - 6
  - 12
  - 24
pred_residuals: False
last_kernel_size: 3
pad: "circular"
mlp_ratio: 4.0
dropout: 0.0
attention_dropout: 0.0
stochastic_depth_prob: 0.2
norm_layer: None # Default is LayerNorm
dilation: # Decoder params
  - 1
  - 2
  - 4
  - 8
n_layers: # Decoder params
  - 1
  - 1
  - 1
  - 1