defaults:
  - /exp/modules/blocks@core_block: conv_block
  - /exp/modules/blocks@down_sampling_block: max_pool
  - /exp/modules/blocks@up_sampling_block: bilinear_upsample
  - /exp/modules/activations@activation: relu

_target_: models.unet.UNet
_recursive_: false
ch_width:
  - 6
  - 64
  - 128
  - 256
  - 512
n_out: 3
dilation:
  - 1
  - 1
  - 1
  - 1
n_layers:
  - 2
  - 2
  - 2
  - 2
pred_residuals: False
last_kernel_size: 3
pad: "circular"
