# SPDX-FileCopyrightText: 2026 Samudra Authors
#
# SPDX-License-Identifier: CC0-1.0

type: local
output_dir: .LOCAL/searches
# By default, use every GPU visible to the current machine.
# max_concurrent: 4
