# SPDX-FileCopyrightText: 2026 Samudra Authors
#
# SPDX-License-Identifier: CC0-1.0

type: slurm_allocation
output_dir: .LOCAL/searches
# By default, use every GPU in the current Slurm allocation.
# max_concurrent: 8
