# SPDX-FileCopyrightText: 2026 Samudra Authors
#
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=../schemas/EvalConfig.json

debug: false
save_zarr: true
disk_mode: true
inference_time:
  start: "2014-10-10"
  end: "2022-12-24"
num_model_steps_forward: 25

experiment:
  name: samudra_om4_v2_eval
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: disabled
    project: default
data: !include ../data/om4.yaml
model: !include model.yaml
