# SPDX-FileCopyrightText: 2026 Samudra Authors
#
# SPDX-License-Identifier: CC0-1.0

debug: false
disk_mode: true
pin_mem: true
save_freq: 1
validation_image_log_freq: 1
epochs: 12
batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 0.0004
scheduler: null
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [1, 3, 6, 12]
data_stride: [1]
steps: [4]
step_transition: []
preemptible: false
backend: auto
experiment:
  name: perceiver-structured-inverse-candidate
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online
    entity: ocean_emulators
    project: default
    tags: [torch, om4-2deg, structured-perceiver, inverse-search, adaptive-search]
    notes: Structured Perceiver inverse search using adaptive data parallelism on Torch.
data: !include data_torch.yaml
model: !include model.yaml
