# SPDX-FileCopyrightText: 2026 Samudra Authors
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=../schemas/VizConfig.json

base_output_dir: .LOCAL
name: perceiver-spatial-grid-quarterdeg-viz
dataset_name: OM4 quarter degree
data: !include ../perceiver_spatial_grid_1deg/data.yaml
basins_location:
  type: s3
  anon: true
  bucket: m2lines-pubs
  path: Samudra/basins/basin_masks_quarterdeg.zarr
  endpoint_url: https://nyu1.osn.mghpcc.org
groundtruth_time_range:
  start: "2014-10-20"
  end: "2022-12-24"
runs:
  - name: perceiver-spatial-grid-quarterdeg
    location: .LOCAL/perceiver-spatial-grid-quarterdeg-eval/predictions.zarr
