# ~
# Entrypoint to run a training job on a single-node, 8x A100 GPU cluster with skypilot.
# ~
#
# First, make sure that all your credentials are set up:
# ```
# sky check -v
# ```
# You will generally need to create a dedicated IAM user for skypilot, and put
# your lambda credentials in ~/.lambda_cloud/ -- the `sky check -v` command has more details.
#
# To create or re-use a cluster:
# ```
# export WANDB_API_KEY=<my-key>  # Get your key at https://wandb.ai/authorize
# uv run sky launch train.sky.yaml --env-file <my-env>.env --env WANDB_API_KEY
# ```
# As the job progresses, skypilot will provide commands to locally monitor each stage.
#
#
# To get debug traces when running `sky` commands, set this environment variable:
# ```
# export SKYPILOT_DEBUG=true
# ```
resources:
  # Optional; if left out, automatically pick the cheapest cloud.
  cloud: lambda
  # 8x NVIDIA A100-80GB GPU
  accelerator: A100-80GB:8
  disk_tier: best

# NOTE: Remember to pass environment variables with `--env` or `--env-file`
# NOTE: All `null` values must be specified in order for this script to run!
envs:
  # Secrets
  # As of v0.9.3, `sky` supports passing in secrets via a dotenv file! So, you can specify these with `--env-file`.
  # To pass in secrets, we recommend setting environment variable and then ONLY passing in the name via `--env`
  WANDB_API_KEY: null # e.g. `--env WANDB_API_KEY`
  # Run `sky check aws -v` to verify that AWS storage is properly set up.
  # If you still hit permission issues, consider making a dedicated SkyPilot IAM via these docs:
  # https://docs.skypilot.co/en/latest/cloud-setup/cloud-permissions/aws.html#dedicated-skypilot-iam-user

  OSN_KEY_ID: null
  OSN_KEY_SECRET: null

  CONFIG: null
  OUTPUTS_BUCKET: oa-fomo-outputs
  NAME: null # wandb train experiment name (and used for downstream tasks)
  ARGS: ""

#### Shared setup, please ensure this is the same as in all *.sky.yaml files ####
file_mounts:
  # TODO(alxmrs): Consider adding a data/ COPY file_mount here once `mount_options` feature exists.
  # The current method of copying (in the setup section, below) is faster.

  /outputs:
    source: s3://${OUTPUTS_BUCKET}
    mode: MOUNT_CACHED

workdir: .

setup: |
  set -ex

  rclone config create nyu-osn s3 provider=AWS endpoint=https://nyu1.osn.mghpcc.org/ access_key_id="$OSN_KEY_ID" secret_access_key="$OSN_KEY_SECRET"

  mkdir -p ~/data/
  rclone copy --progress nyu-osn:emulators/jr7309/data/om4_halfdeg/ ~/data --ignore-existing --transfers=32

  mkdir -p ~/basins/
  rclone copy --progress nyu-osn:emulators/jr7309/basins ~/basins

#### End of shared setup ####

run: |
  set -ex

  MASTER_ADDR=$(echo "$SKYPILOT_NODE_IPS" | head -n1)
  echo "Starting distributed training, head node: $MASTER_ADDR"

  DATA_ROOT=$(realpath ~/data)

  # Explicit check for torchrun
  if ! command -v torchrun >/dev/null 2>&1; then
      echo "ERROR: torchrun command not found" >&2
      exit 1
  fi

  uv run torchrun \
    --standalone \
    --nnodes=$SKYPILOT_NUM_NODES \
    --nproc_per_node=$SKYPILOT_NUM_GPUS_PER_NODE \
    --master_addr=$MASTER_ADDR \
    --master_port=8008 \
    --node_rank=${SKYPILOT_NODE_RANK} \
    -m ocean_emulators.train "${CONFIG}" \
    --experiment.name="${NAME}" \
    --experiment.data_root="${DATA_ROOT}" \
    --experiment.base_output_dir=/outputs/  \
    --experiment.wandb.mode=online \
    ${ARGS}
