# @package _global_
defaults:
  - _self_
  - unet: unet_3D

wandb:
  mode: disabled # online, disabled
  project: 3D_ocean_emu
  entity: suryadheeshjith
  group: null
  tags: null
  notes: null

### experiment args
experiment: eval
output_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}}
data_overlay: ''
path_dir: /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/Preds
data_dir: /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/data # /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/.LOCAL/save_data/2024-03-06-save_data_test/data # /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/data
steps: 4

######
pred_region: null # "global_21"
model_name_replace: null
pred_names: null
pred_paths: null

ckpt_path: null # changed in command args
network: unet # changed in command args
loss: mse

save_test_data: false # change if already saved in prior experiments
save_clim_data: false # change if already saved in prior experiments
run_gen_pred: false
run_gen_short_pred: false
run_full_pred: false
run_short_pred: false
run_plot_metrics: false
run_long_metrics: true
run_plot_animation: false
####

device: "cuda" # keep this cuda to get preds in gpu

# Parameters
exp_num_in: "3D"
exp_num_extra: "3D"
exp_num_out: "3D"
train_region: null
region: null # "global_21"
depth_mode: null
N_samples:  4000 #4000
N_val:  140 #300
N_test: 600 #500
interval: 1
hist: 0
lag: 1
lam: 0.05
Nb: 0 # 4 # Should technically be 0 when lateral is False but most of the code uses Nb
factor: 10
lateral: false
