# @package _global_
defaults:
  - _self_
  - unet: adamunet

wandb:
  mode: disabled # online, disabled
  project: ocean_emu
  entity: suryadheeshjith
  group: null
  tags: null
  notes: null

### experiment args
experiment: eval
output_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}}
data_overlay: ''
path_dir: /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/Preds
data_dir: /pscratch/sd/s/suryad/data # /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/.LOCAL/save_data/2024-03-06-save_data_test/data # /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/data
steps: 4

######
model_name_replace: Foundation Adam UNet
pred_region: null # "global_21"
###############
### g1 g1
pred_names: null
  # - Adam UNet
pred_paths: null
  # - "/scratch/sd5313/M2Lines/emulator/Ocean_Emulator/Preds/Adam UNet_Train_global_1_Test_global_1_Test_in_u_v_T_ext_tau_u_tau_v_t_ref__outu_v_T_N_train_4000_Lateral_Data_025_no_smooth"
###############

###############
### g1 g2x
# pred_names:
#   - Adam UNet
# pred_paths:
#   - "/scratch/sd5313/M2Lines/emulator/Ocean_Emulator/Preds/Adam UNet Train1Eval2x_Train_global_1_Test_global_2x_Test_in_u_v_T_ext_tau_u_tau_v_t_ref__outu_v_T_N_train_4000_Lateral_Data_025_no_smooth"

###############

###############
### g1_2x g4x
# pred_names: null
# pred_paths: null
###############

ckpt_path: null # changed in command args
network: unet # changed in command args
loss: mse

save_test_data: false # change if already saved in prior experiments
save_clim_data: false # change if already saved in prior experiments
run_gen_pred: true
run_gen_short_pred: true
run_full_pred: false
run_short_pred: false
run_plot_metrics: false
run_long_metrics: false
run_plot_animation: false
####

device: "cuda" # keep this cuda to get preds in gpu

# Parameters
exp_num_in: "10"
exp_num_extra: "12"
exp_num_out: "6"
train_region: null
region: null # "global_21"
N_samples: 4000
N_val: 200
N_test: 3000
interval: 1
hist: 0
lag: 1
lam: 0.05
Nb: 0 # 4 # Should technically be 0 when lateral is False but most of the code uses Nb
factor: 10
lateral: false
