# @package _global_
defaults:
  - _self_

### experiment args
experiment: save_data
output_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}}
data_overlay: ''
grid_path: /scratch/as15415/Data/CM2x_grids/Grid_cm25_Vertices.nc
data_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}, 'data'}
rand_seed: 1
device: "cuda"

# Parameters
exp_num_in: "3"
exp_num_extra: "12"
exp_num_out: "2"
region: "Gulf_Stream_Ext3"
N_samples: 4000 #4000
N_val: 300 #300
N_test: 500 #500
steps: 8
interval: 1
hist: 0
lag: 1
lam: 0.05
Nb: 4
factor: 10
lateral: true
