# @package _global_
defaults:
  - _self_
  - unet: unet

wandb:
  mode: disabled # online, disabled
  project: ocean_emu
  entity: suryadheeshjith
  group: null
  tags: null
  notes: null

### experiment args
experiment: train_unet
output_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}}
data_overlay: ''
grid_path: /scratch/as15415/Data/CM2x_grids/Grid_cm25_Vertices.nc
nets_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}, 'saved_nets'}
rand_seed: 1


#####
region: "Gulf_Stream_Ext"
network: "unet"
train_data_path: /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/.LOCAL/save_data_tensor/2024-04-01-save_data_tensor_recunet_Gulfext_with_wet/data/train_data_steps_0_Gulf_Stream_Ext_Test_in_um_vm_Tm_ext_tau_u_tau_v_t_ref__outum_vm_Tm_N_train_4000_Lateral_Data_025_no_smooth.pt
val_data_path: /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/.LOCAL/save_data_tensor/2024-04-01-save_data_tensor_recunet_Gulfext_with_wet/data/val_data_steps_0_Gulf_Stream_Ext_Test_in_um_vm_Tm_ext_tau_u_tau_v_t_ref__outum_vm_Tm_N_train_4000_Lateral_Data_025_no_smooth.pt
wet_path: /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/.LOCAL/save_data_tensor/2024-04-01-save_data_tensor_recunet_Gulfext_with_wet/data/wet_steps_0_Gulf_Stream_Ext_Test_in_um_vm_Tm_ext_tau_u_tau_v_t_ref__outum_vm_Tm_N_train_4000_Lateral_Data_025_no_smooth.pt
scheduler: False
#####


device: "cuda"
distributed: True
num_workers: 0 # Keep 0
pin_mem: False # Keep false
save_freq: 5
epochs: 100
batch_size: 6
grad_clip: True # Keep true

# Optimizer
lr: 2e-4
T: 10 # CosineA / CosineAWarm param

# Parameters
exp_num_in: "3"
exp_num_extra: "12"
exp_num_out: "2"
N_samples: 4000 #4000
N_val: 300 #300
N_test: 500 #500
steps: 8 # 8
interval: 1
hist: 0
lag: 1
lam: 0.05
Nb: 4
factor: 10
lateral: true

### Do not touch these
# distributed args
dist_url: null
world_size: null
rank: null
gpu: null
dist_backend: null
