# @package _global_
defaults:
  - _self_
  - unet: unet

wandb:
  mode: disabled # online, disabled
  project: ocean_emu
  entity: suryadheeshjith
  group: null
  tags: null
  notes: null

### experiment args
experiment: train
output_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}}
data_overlay: ''
grid_path: /scratch/as15415/Data/CM2x_grids/Grid_cm25_Vertices.nc
data_dir: /scratch/sd5313/M2Lines/emulator/Ocean_Emulator/.LOCAL/save_data/2024-04-11-save_data_global21/data
nets_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}, 'saved_nets'}
rand_seed: 1


#####
region: "global_21"
network: "unet"
scheduler: False
loss: mse
testing: False
#####


device: "cuda"
distributed: True
num_workers: 0 # Keep 0
pin_mem: False # Keep false
save_freq: 5
epochs: 100
batch_size: 32
# grad_clip: False

# Optimizer
lr: 2e-4
T: 10 # CosineA / CosineAWarm param

# Parameters
exp_num_in: "10"
exp_num_extra: "12"
exp_num_out: "6"
N_samples: 4000 #4000
N_val: 300 #300
N_test: 500 #500
steps: 4
interval: 1
hist: 0
lag: 1
lam: 0.05
Nb: 0
factor: 10
lateral: false

### Do not touch these
# distributed args
dist_url: null
world_size: null
rank: null
gpu: null
dist_backend: null
