defaults:
  - _self_
  - compute: slurm # must be slurm or local
  - exp: ???

base_output_dir: /pscratch/sd/s/suryad/Ocean_Emulator
data_dir: /pscratch/sd/s/suryad/data
pred_dir: /pscratch/sd/s/suryad/Ocean_Emulator/Preds
experiment: ???
sub_dir: ${experiment}
name: ???

experiment_dir: ???

hydra:
  job:
    name: ${name}
  callbacks:
    log_job_return_callback:
      _target_: submitit_hydra.LogJobReturnCallback
