defaults:
  - _self_
  - compute: slurm # must be slurm or local
  - exp: ???

base_output_dir: ${oc.env:BASE_OE_DIR}
data_dir: /vast/sd5313/data/m2lines/3D_ocean_data
pred_dir: ${oc.env:BASE_OE_DIR}/Preds
experiment: ???
sub_dir: ${experiment}
name: ???

experiment_dir: ???

hydra:
  job:
    name: ${name}
  callbacks:
    log_job_return_callback:
      _target_: submitit_hydra.LogJobReturnCallback
