defaults:
  - _self_
  - compute: slurm # must be slurm or local
  - exp: ???

base_output_dir: ${oc.env:PWD}
data_dir: /pscratch/sd/s/suryad/data
pred_dir: ${oc.env:PWD}/Preds
experiment: ???
sub_dir: ${experiment}
name: ???

experiment_dir: ???

hydra:
  job:
    name: ${name}
  callbacks:
    log_job_return_callback:
      _target_: submitit_hydra.LogJobReturnCallback
