debug: false
save_zarr: true
disk_mode: true
inference:
  start_time: "0311-01-01"
  end_time: "0351-01-01"
ckpt_path: /global/homes/j/jrayshi/scratch/Github/Ocean_Emulator/.LOCAL/2025-05-06-train-samudra-perlmutter-cm4-m2lines-OHCOn-wfo-fix3/saved_nets/best_inference_ckpt.pt # Fill in script
num_model_steps_forward: 20 #370

experiment:
  base_name: eval
  sub_name: samudra-perlmutter-cm4-m2lines-OHCOn-wfo-fix3-rollout50epochs
  rand_seed: 15
  base_output_dir: .LOCAL
  gantry: false
  cluster_data_dir: /dvs_ro/cfs/cdirs/m4874/suryad/data/
  wandb:
    mode: online
    project: emulator-cm4-sensitivity  #3D_ocean_emu_CM4_eval_inputs_311
    entity: m2lines #jrayshi-new-york-university
    group: samudra-eval-cm4
  network: Samudra
  prognostic_vars_key: thermo_dynamic_all
  boundary_vars_key: tau_hfds_wfo

data:
  data_path: cm4_piControl_ocean_200yr_full_chunked.zarr
  data_means_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/centering.nc
  data_stds_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/scaling-full-field.nc
  static_data_vars:
    - sea_surface_fraction
    - hfgeou
  scaling_residuals_file: null
  num_workers: 4
  hist: 1


samudra:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  corrector:
    non_negative_corrector_names: 
      - "so"
    ocean_heat_corrector: true
    salinity_range_corrector: false 
    zos_range_corrector: false
    zos_gmean_corrector: false
    
  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"