
debug: true
save_zarr: true
disk_mode: true
inference:
  start_time: "2014-10-10"
  end_time: "2022-12-24"
ckpt_path: /this/path/does/not/exist # Fill in script
num_model_steps_forward: -1

experiment:
  base_name: eval
  sub_name: local_om4_samudra
  rand_seed: 15
  base_output_dir: /pscratch/sd/s/suryad/Ocean_Emulator/.LOCAL
  gantry: false
  cluster_data_dir: null
  wandb:
    mode: online
    project: ocean-emulators
    entity: m2lines
    group: samudra-eval-om4
  network: Samudra
  prognostic_vars_key: thermo_dynamic_all
  boundary_vars_key: tau_hfds_hfds_anom

data:
  data_path: 3D_data_OM4_5daily_v0.2.1_with_hfds_anomalies
  data_means_path: 3D_data_OM4_5daily_v0.2.1_with_hfds_anomalies_means
  data_stds_path: 3D_data_OM4_5daily_v0.2.1_with_hfds_anomalies_stds
  scaling_residuals_file: null
  time_delta: 5
  num_workers: 4
  hist: 1


samudra:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"