debug: true
disk_mode: true
inference:
  start_time: 311-01-01
  end_time: 351-01-01
ckpt_path: /pscratch/sd/s/suryad/Ocean_Emulator/temp/2025-02-09-train-samudra-train-cm4-thermodynamic-scheduler-batchsize3-so-corrector/saved_nets/convnextunet_epoch_45_best_inference_steps_4_all_Lateral_Data_025_no_smooth.pt
num_model_steps_forward: 20
record_every: 10

experiment:
  name: eval
  sub_name: local_cm4_samudra_thermo
  rand_seed: 15
  base_output_dir: .LOCAL
  gantry: false
  cluster_data_dir: null
  wandb:
    mode: online
    project: ocean-emulator
    entity: ai2cm
    group: samudra-inference-2in2out
  network: convnextunet
  exp_num_in: 3D_all
  exp_num_extra: 3D_all
  exp_num_out: 3D_all

data:
  data_path: cm4_piControl_ocean_200yr_full.zarr
  data_means_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/centering.nc
  data_stds_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/scaling-full-field.nc
  scaling_residuals_file: null
  depth_mode: all
  time_delta: 5
  num_workers: 4
  hist: 1


unet:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  corrector:
    non_negative_corrector_names:
      - "so"

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"
