debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 120
batch_size: 3
learning_rate: 0.0001
scheduler: false
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
validate_using_ema: true
train:
  start_time: 151-01-06
  end_time: 306-01-01
val:
  start_time: 306-01-01
  end_time: 311-01-01
inference:
  - start_time: 151-01-06
    end_time: 171-01-11
  - start_time: 171-01-06
    end_time: 191-01-11
  - start_time: 191-01-06
    end_time: 211-01-11
  - start_time: 211-01-06
    end_time: 231-01-11
  - start_time: 231-01-06
    end_time: 251-01-11
  - start_time: 251-01-06
    end_time: 271-01-11
  - start_time: 271-01-06
    end_time: 291-01-11
  - start_time: 291-01-06
    end_time: 311-01-11
data_stride: [1]
steps: [4]
step_transition: []

distributed:
  enabled: true
  dist_url: null
  world_size: null
  rank: null
  gpu: null
  dist_backend: null

experiment:
  name: train
  sub_name: cm4_samudra
  rand_seed: 1
  base_output_dir: /results
  gantry: true
  cluster_data_dir: /
  wandb:
    mode: online
    project: ocean-emulator
    entity: ai2cm
    group: samudra-train-2in2out
  network: convnextunet
  exp_num_in: 3D_all
  exp_num_extra: 3D_all
  exp_num_out: 3D_all

data:
  data_path: /climate-default/2025-02-10-cm4-piControl-ocean-200yr-dataset/data_uncompressed.zarr
  data_means_path: /statsdata/centering.nc
  data_stds_path: /statsdata/scaling-full-field.nc
  scaling_residuals_file: null
  depth_mode: all
  time_delta: 5
  num_workers: 4
  hist: 1


unet:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  corrector:
    non_negative_corrector_names:
      - "so"
    ocean_heat_corrector: false

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"
