debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 70
batch_size: 4
learning_rate: 0.0002
scheduler: true
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
train:
  start_time: "1975-01-03"
  end_time: "2013-10-05"
val:
  start_time: "2013-10-05"
  end_time: "2014-10-05"
inference:
  - start_time: "1975-01-03"
    end_time: "1985-01-03"
  - start_time: "1985-01-03"
    end_time: "1995-01-03"
  - start_time: "1995-01-03"
    end_time: "2005-01-03"
  - start_time: "2004-10-05"
    end_time: "2014-10-05"
data_stride: [1]
steps: [4]
step_transition: []
backend: auto

experiment:
  base_name: train
  sub_name: om4_samudra
  rand_seed: 5
  base_output_dir: train
  gantry: false
  cluster_data_dir: /pscratch/sd/s/suryad/data
  wandb:
    mode: online
    project: ocean-emulator
    entity: m2lines
    group: samudra-train-om4
  network: Samudra
  prognostic_vars_key: thermo_all
  boundary_vars_key: tau_hfds_hfds_anom

data:
  data_path: 3D_data_OM4_5daily_v0.2.1_with_hfds_anomalies
  data_means_path: 3D_data_OM4_5daily_v0.2.1_with_hfds_anomalies_means
  data_stds_path: 3D_data_OM4_5daily_v0.2.1_with_hfds_anomalies_stds
  static_data_paths:
    sea_surface_fraction: cm4_sea_surface_fraction_fixed.zarr
    hfgeou: cm4_geothermal_hf_fixed.zarr
  scaling_residuals_file: null
  time_delta: 5
  num_workers: 4
  hist: 1

samudra:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"

  corrector:
    non_negative_corrector_names: null
    ocean_heat_corrector: true
