name: train
sub_name: local_cm4_samudra_thermo
rand_seed: 1
base_output_dir: .LOCAL
debug: true
gantry: false
cluster_data_dir: null

wandb:
  mode: disabled
  project: 3D_ocean_emu_CM4
  entity: suryadheeshjith

training:
  distributed: true
  disk_mode: true
  num_workers: 4
  pin_mem: true
  save_freq: 5
  epochs: 120
  batch_size: 2 # 4
  learning_rate: 0.0002
  scheduler: false
  loss: mse
  network: convnextunet
  exp_num_in: 3D_noFast_all
  exp_num_extra: 3D_all
  exp_num_out: 3D_noFast_all
  finetune: false
  resume_ckpt_path: null

data:
  wet_file: CM4_5daily_v0.4.0_wetmask
  data_path: 2024-11-12-cm4-piControl-ocean-200yr-monthly/015*.nc
  data_means_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/centering.nc
  data_stds_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/scaling-full-field.nc
  scaling_residuals_file: null
  depth_mode: all
  data_stride: [1]
  steps: [4]
  step_transition: []
  hist: 1
  data_percent: 1.0
  time_delta: 5
  train:
    start_time: 151-01-06
    end_time: 153-01-01
  val:
    start_time: 153-01-01
    end_time: 154-01-01
  inference:
    - start_time: 153-01-06
      end_time: 155-01-06
    - start_time: 153-01-06
      end_time: 155-01-06
    - start_time: 156-01-06
      end_time: 157-01-06
    - start_time: 157-01-06
      end_time: 158-01-06
    - start_time: 158-01-06
      end_time: 159-01-06
    - start_time: 159-01-06
      end_time: 160-01-06
    - start_time: 160-01-06
      end_time: 161-01-06
    - start_time: 161-01-06
      end_time: 162-01-06
  inference_epochs: [-1]

unet:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"
