# yaml-language-server: $schema=schemas/TrainConfig.json

debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 70
batch_size: 3
#  # Experiment configurations
#  lr_experiments:
#    - (skip) learning_rate: 0.0001   # 6× smaller than baseline
#    - x learning_rate: 0.0002   # 3× smaller than baseline
#    -   learning_rate: 0.0004   # 1.5× smaller than baseline
#    - x learning_rate: 0.0006   # Current baseline
#    -   learning_rate: 0.001    # 1.7× larger than baseline
#    -   learning_rate: 0.002    # 3.3× larger than baseline
#    -   learning_rate: 0.004    # 6.7× larger than baseline
#    - (skip) learning_rate: 0.008    # 13× larger than baseline (aggressive)
learning_rate: 0.0002
scheduler: { type: cosine }
kill_after_n_epochs: 20
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: []
data_percent: 1.0
train_time:
  start: "1975-01-03"
  end: "2013-10-05"
val_time:
  start: "2013-10-05"
  end: "2014-10-05"
inference_times:
  - start: "1975-01-03"
    end: "1980-01-03"
  - start: "1980-01-03"
    end: "1985-01-03"
  - start: "1985-01-03"
    end: "1990-01-03"
  - start: "1990-01-03"
    end: "1995-01-03"
  - start: "1995-01-03"
    end: "2000-01-03"
  - start: "2000-01-03"
    end: "2005-01-03"
  - start: "2005-01-03"
    end: "2010-01-03"
  - start: "2010-01-03"
    end: "2014-10-05"
data_stride: [1]
steps: [4]
step_transition: []
preemptible: false

backend: auto

experiment:
  name: om4_samudra_halfdeg_wide_v0_lr_v3_0002
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online
    project: ocean-emulators
    entity: m2lines
  network: Samudra
  prognostic_vars_key: thermo_dynamic_all
  boundary_vars_key: tau_hfds_hfds_anom
data:
  !include data/public.yaml

samudra:
  checkpointing: all
  ch_width: [157, 280, 380, 480, 520]
  n_out: 154
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 2
    norm: "batch"

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"

  corrector:
    non_negative_corrector_names: null
    ocean_heat_corrector: false