debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 120
batch_size: 2 # 4
learning_rate: 0.0001
scheduler: false
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
train:
  start_time: "1975-01-03"
  end_time: "2013-10-05"
val:
  start_time: "2013-10-05"
  end_time: "2014-10-05"
inference:
  - start_time: "1975-01-03"
    end_time: "1985-01-03"
  - start_time: "1985-01-03"
    end_time: "1995-01-03"
  - start_time: "1995-01-03"
    end_time: "2005-01-03"
  - start_time: "2004-10-05"
    end_time: "2014-10-05"
data_stride: [1]
steps: [4]
step_transition: []
backend: auto

experiment:
  name: train
  sub_name: jder_test_om4
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online
    project: ocean-emulators
    entity: m2lines
    group: samudra-train-om4
  network: convnextunet
  exp_num_in: 3D_all
  exp_num_extra: 3D_all_hfds_anom
  exp_num_out: 3D_all
data:
  data_root: s3://emulators/sd5313/Samudra
  data_values_path: OM4
  data_means_path: OM4_means
  data_stds_path: OM4_stds
  engine: zarr
  scaling_residuals_file: null
  depth_mode: all
  time_delta: 5
  num_workers: 0
  hist: 0


unet:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  corrector:
    non_negative_corrector_names:
      - "so"

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"
