debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 70
batch_size: 1
learning_rate: 0.0002
scheduler: true
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
train:
  start_time: "1975-01-03"
  end_time: "1975-05-03"
  # end_time: "2013-10-05"
val:
  start_time: "2013-10-05"
  end_time: "2014-10-05"
inference:
  - start_time: "2014-11-05"
    end_time: "2015-11-05"
data_stride: [1]
steps: [4]
step_transition: []
backend: auto

experiment:
  base_name: train
  sub_name: local_om4_samudra
  rand_seed: 15
  base_output_dir: .LOCAL
  gantry: false
  wandb:
    mode: disabled
    project: ocean-emulators
    entity: m2lines
    group: samudra-train-om4
  network: convnextunet
  exp_num_in: 3D_all
  exp_num_extra: 3D_all_hfds_anom
  exp_num_out: 3D_all
data:
  data_path: /home/jder/data/om4.zarr
  data_means_path: /home/jder/data/om4_means.zarr
  data_stds_path: /home/jder/data/om4_stds.zarr
  scaling_residuals_file: null
  depth_mode: all
  time_delta: 5
  num_workers: 0
  hist: 1


unet:
  # ch_width: [157, 200, 250, 300, 400]
  ch_width: [157,200]
  n_out: 77
  # dilation: [1, 2, 4, 8]
  # n_layers: [1, 1, 1, 1]
  dilation: [1]
  n_layers: [1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"
