debug: true
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 120
batch_size: 2 # 4
learning_rate: 0.0001
scheduler: false
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
train:
  start_time: "0151-01-06"
  end_time: "0154-01-01"
val:
  start_time: "0306-01-01"
  end_time: "0307-01-01"
inference:
  - start_time: "0151-01-06"
    end_time: "0151-02-11"
  - start_time: "0153-01-06"
    end_time: "0155-01-11"
  - start_time: "0155-01-06"
    end_time: "0157-01-11"
  - start_time: "0157-01-06"
    end_time: "0159-01-11"
  - start_time: "0159-01-06"
    end_time: "0161-01-11"
  - start_time: "0161-01-06"
    end_time: "0163-01-11"
  - start_time: "0163-01-06"
    end_time: "0165-01-11"
  - start_time: "0309-01-06"
    end_time: "0311-01-11"
data_stride: [1]
steps: [4]
step_transition: []
backend: auto

experiment:
  base_name: train
  sub_name: local_cm4_samudra
  rand_seed: 15
  base_output_dir: .LOCAL
  gantry: false
  cluster_data_dir: null
  wandb:
    mode: disabled
    project: 3D_ocean_emu_CM4
    entity: suryadheeshjith
  network: Samudra
  prognostic_vars_key: thermo_dynamic_all
  boundary_vars_key: tau_hfds
data:
  data_path: cm4_piControl_ocean_200yr_full_chunked.zarr
  data_means_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/centering.nc
  data_stds_path: 2024-11-12-cm4-piControl-ocean-200yr-dataset-stats/scaling-full-field.nc
  static_data_vars:
    - sea_surface_fraction
    - hfgeou
  scaling_residuals_file: null
  num_workers: 4
  hist: 0


samudra:
  ch_width: [157, 200, 250, 300, 400]
  n_out: 77
  dilation: [1, 2, 4, 8]
  n_layers: [1, 1, 1, 1]
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  core_block:
    block_type: "conv_next_block"
    kernel_size: 3
    activation: "capped_gelu"
    upscale_factor: 4
    norm: "batch"

  corrector:
    non_negative_corrector_names:
      - "so"
    ocean_heat_corrector: true

  down_sampling_block: "avg_pool"
  up_sampling_block: "bilinear_upsample"