# yaml-language-server: $schema=schemas/VizConfig.json

base_output_dir: ".LOCAL"
name: "viz_om4_onedeg"
dataset_name: "OM4"
groundtruth_location: "/orcd/data/abodner/002/cody/OM4.zarr"
basins_location:
  type: s3
  bucket: "emulators"
  path: "jr7309/basins/basin_masks_original.zarr"
  endpoint_url: "https://nyu1.osn.mghpcc.org"
groundtruth_time_range:
  start: "2014-10-20"
  end: "2022-12-24"
runs:
  - name: "test_eval_om4_10-27"
    location: ".LOCAL/test_eval_om4_10-27/predictions.zarr"
