# SPDX-FileCopyrightText: 2026 Ocean Emulator Authors
#
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=../schemas/EvalConfig.json

debug: false
save_zarr: true
disk_mode: true
inference_time:
  start: "2014-10-05"
  end: "2015-10-05"
num_model_steps_forward: 25

experiment:
  name: kr1_fomo_multiscale_halfdeg_eval
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online
    project: default
    entity: ocean_emulators
    group: kr1_multiscale_eval
    tags:
      - kr1
      - eval
      - halfdeg
      - multiscale
      - fomo

data:
  dataset:
    type: om4
    prognostic_vars_key: thermo_dynamic_all
    boundary_vars_key: tau_hfds
  static_data_vars: []
  concurrent_compute: true
  sources:
    - data_location: om4_halfdeg_v4/OM4.zarr
      data_means_location: om4_halfdeg_v4/OM4_means.zarr
      data_stds_location: om4_halfdeg_v4/OM4_stds.zarr
    - data_location: om4_onedeg_v3/OM4.zarr
      data_means_location: om4_onedeg_v3/OM4_means.zarr
      data_stds_location: om4_onedeg_v3/OM4_stds.zarr
    - data_location: om4_quarterdeg_v2/OM4.zarr
      data_means_location: om4_quarterdeg_v2/OM4_means.zarr
      data_stds_location: om4_quarterdeg_v2/OM4_stds.zarr

model: !include model.yaml
