# yaml-language-server: $schema=../schemas/TrainConfig.json

debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 70
batch_size: 2
learning_rate: 0.0006
scheduler: { type: cosine }
loss:
  type: dynamic
  metric: mse
finetune: false
resume_ckpt_path: null
inference_epochs: []
data_percent: 1.0
train_time:
  start: "1975-01-03"
  end: "2013-10-05"
val_time:
  start: "2013-10-05"
  end: "2014-10-05"
inference_times:
  - start: "1975-01-03"
    end: "1976-01-03" # "1985-01-03"
  - start: "1985-01-03"
    end: "1986-01-03" # "1995-01-03"
  - start: "1995-01-03"
    end: "1996-01-03" # "2005-01-03"
  - start: "2004-10-05"
    end: "2005-10-05" # "2014-10-05"
data_stride: [1]
steps: [4]
step_transition: []
preemptible: false

backend: auto

experiment:
  name: fomo_om4
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: disabled
    project: default
  prognostic_vars_key: thermo_dynamic_all
  boundary_vars_key: tau_hfds_hfds_anom
  train_schedule: match
data:
  static_data_vars: []
  concurrent_compute: true
  loading:
    type: cpu
    num_workers: 4
  sources:
    - data_location: OM4.zarr
      data_means_location: OM4_means.zarr
      data_stds_location: OM4_stds.zarr
    - data_location: om4_onedeg_v3/OM4.zarr
      data_means_location: om4_onedeg_v3/OM4_means.zarr
      data_stds_location: om4_onedeg_v3/OM4_stds.zarr
model: !include model.yaml
