#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pandas>2.0",
#     "pandas-stubs",
# ]
# ///
"""
Training Log Parser CLI

This script parses training log files into a CSV format using pandas and argparse.

Generated by Claude 3.5 Haiku in a quick conversation:
    https://claude.ai/share/b1edac41-72c5-436e-8540-201f56f3c83c
"""

import argparse
import re
from pathlib import Path

import pandas as pd


def parse_training_logs(
    input_file: Path, output_file: Path | None = None
) -> pd.DataFrame:
    """
    Parse training log messages and extract relevant information to a CSV using pandas.

    Args:
        input_file: Path to the input log file
        output_file: Path to the output CSV file (optional)

    Returns:
        Parsed DataFrame of training logs
    """
    # Regex pattern to extract key information from log lines
    pattern = (
        r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - INFO - Training Epoch: "
        r"\[(\d+)\]  \[\s*(\d+)/(\d+)\]  eta: ([\d:]+)  lr: ([\d.]+)  "
        r"loss: ([\d.]+) \(([\d.]+)\)  time: ([\d.]+)\(([\d.]+)\)  "
        r"data: ([\d.]+)\(([\d.]+)\)  max cpu mem: (\d+)  max gpu mem: (\d+)"
    )

    # Read input file
    with open(input_file, "r") as f:
        log_content = f.read()

    # Find all matches
    matches = re.findall(pattern, log_content)

    # Create DataFrame
    df = pd.DataFrame(
        matches,
        columns=[
            "Timestamp",
            "Epoch",
            "Batch",
            "Total Batches",
            "ETA",
            "Learning Rate",
            "Current Loss",
            "Average Loss",
            "Time",
            "Avg Time",
            "Data Time",
            "Avg Data Time",
            "Max CPU Mem",
            "Max GPU Mem",
        ],
    )

    # Convert numeric columns to appropriate types
    numeric_columns = [
        "Epoch",
        "Batch",
        "Total Batches",
        "Learning Rate",
        "Current Loss",
        "Average Loss",
        "Time",
        "Avg Time",
        "Data Time",
        "Avg Data Time",
        "Max CPU Mem",
        "Max GPU Mem",
    ]

    for col in numeric_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # Convert timestamp column
    df["Timestamp"] = pd.to_datetime(df["Timestamp"], format="%Y-%m-%d %H:%M:%S,%f")

    # Save to CSV if output file is specified
    if output_file:
        df.to_csv(output_file, index=False)
        print(f"Parsed {len(df)} log entries to {output_file}")

    return df


def main():
    """
    Main CLI entry point for the log parser.
    """
    # Set up argument parser
    parser = argparse.ArgumentParser(
        description="Parse training log files into a CSV format.",
        epilog="Extract detailed information from machine learning training logs.",
    )

    # Input file argument (required)
    parser.add_argument("input_file", type=Path, help="Path to the input log file")

    # Optional output file argument
    parser.add_argument("-o", "--output", type=Path, help="Path to the output CSV file")

    # Optional flag to show statistics
    parser.add_argument(
        "-s",
        "--stats",
        action="store_true",
        help="Show statistical summary of the logs",
    )

    # Parse arguments
    args = parser.parse_args()

    # Validate input file
    if not args.input_file.is_file():
        print(f"Error: Input file {args.input_file} does not exist.")
        return

    # Parse logs
    df = parse_training_logs(args.input_file, args.output)

    # Show stats if requested
    if args.stats:
        print("\nBasic Statistics:")
        stats_columns = ["Epoch", "Batch", "Current Loss", "Learning Rate"]
        print(df[stats_columns].describe().to_string())


if __name__ == "__main__":
    main()
