#!/bin/bash
#SBATCH --job-name=samudra-perlmutter-cm4-m2lines-OHCOn-wfo-3heatcomps
#SBATCH --output=train/logs/slurm-%j.out
#SBATCH --error=train/logs/slurm-%j.err
#SBATCH --constraint=gpu&hbm80g
#SBATCH --account=m4874
#SBATCH --qos=regular
#SBATCH --mem=110G
#SBATCH --nodes=2           # if the train job is big, use 2 nodes here
#SBATCH --ntasks-per-node=2    # 1 or 2
#SBATCH --cpus-per-task=32
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=none     # This ensures all GPUs are visible to all tasks
#SBATCH --time=04:30:00   # For 1 GPU, 4:30:00 is need to run 30 epoches

set -e

# Load conda environment
#source .venv/bin/activate
module load conda
conda activate emulator311

# Set master node information
export MASTER_ADDR=$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -n 1)
export MASTER_PORT=29400

# Debug info
echo "MASTER_ADDR: $MASTER_ADDR"
echo "MASTER_PORT: $MASTER_PORT"
echo "SLURM_JOB_NODELIST: $SLURM_JOB_NODELIST"
echo "SLURM_NTASKS_PER_NODE: $SLURM_NTASKS_PER_NODE"
echo "SLURM_NNODES: $SLURM_NNODES"

# Run the training script
srun --cpu-bind=cores \
     python src/ocean_emulators/train.py \
     --config configs/train_cm4_other2.yaml \
     --subname $SLURM_JOB_NAME


     # configs/slurm_perlmutter_train_cm4.yaml