# SPDX-FileCopyrightText: 2026 Samudra Authors
#
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=../schemas/TrainConfig.json

debug: false
disk_mode: true
pin_mem: true
save_freq: 1
validation_image_log_freq: 100
epochs: 2
batch_size: 4
preemptible: false
learning_rate: 0.0001
scheduler: null
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: []
train_time:
  start: "1975-08-15"
  end: "1975-12-25"
val_time:
  start: "1975-12-25"
  end: "1976-03-28"
inference_times: []
data_stride: [1]
steps: [1, 2]
step_transition: [2]
backend: cuda

experiment:
  name: rust-loader-qualification
  rand_seed: 15
  base_output_dir: .LOCAL/qualification
  wandb:
    mode: disabled
    project: ocean-emulators
    entity: m2lines
    group: rust-loader-qualification
  data_root: .data_cache/remote-om4

data:
  dataset:
    type: om4
    prognostic_vars_key: thermo_dynamic_5
    boundary_vars_key: tau_hfds
  sources:
    - data_location: OM4.zarr
      data_means_location: OM4_means.zarr
      data_stds_location: OM4_stds.zarr
  loading:
    type: cpu
    num_workers: 4
    persistent_workers: true
  hist: 0
  normalize_before_mask: true
  masked_fill_value: 0.0

model:
  pred_residuals: false
  last_kernel_size: 3
  pad: circular
  gradient_detach_interval: 0

  unet:
    ch_width: [4, 4]
    dilation: [1, 2]
    n_layers: [1, 1]

    core_block:
      block_type: conv_next_block
      kernel_size: 3
      activation: capped_gelu
      upscale_factor: 2
      norm: batch

    down_sampling_block: avg_pool
    up_sampling_block: zonally_periodic_upsample
