# yaml-language-server: $schema=../schemas/EvalConfig.json

debug: false
save_zarr: true
disk_mode: true
inference_time:
  start: "2011-09-13"
  end: "2011-11-30"
num_model_steps_forward: 25

experiment:
  name: samudra_llc_eval
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: disabled
    project: default
  prognostic_vars_key: single_1
  boundary_vars_key: single

data: !include ../data/llc.yaml
model: !include model.yaml
