# yaml-language-server: $schema=../schemas/EvalConfig.json

debug: false
save_zarr: true
disk_mode: true
inference_time:
  start: "2012-10-01"
  end: "2012-10-04"
inference_stride: 6
num_model_steps_forward: 2

experiment:
  name: 2026-04-24-eval:Samudra_LLC:config_tests_experiment_6
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online
    project: default
  prognostic_vars_key: all
  boundary_vars_key: all

data: !include ../data/llc.yaml
model: !include model_replay_ch_width_normal.yaml
