# yaml-language-server: $schema=../schemas/TrainConfig.json

debug: false
disk_mode: true
pin_mem: true
save_freq: 1
epochs: 5
batch_size: 1
learning_rate: 0.0006
gradient_accumulation_steps: 4
scheduler: { type: cosine }
loss: mse
 # type: dynamic
#  metric: mse
finetune: false
resume_ckpt_path: null
inference_epochs: []
data_percent: 1.0
train_time:
  start: "2011-09-13" # "2011-09-13"
  end: "2011-09-14" # "2012-11-01"
val_time:
  start: "2011-09-15" # "2012-09-01"
  end: "2011-09-16" # "2012-10-01"
inference_times:
  - start: "2012-10-01"
    end: "2012-10-07"
data_stride: [1]
steps: [1]
step_transition: []
preemptible: false

backend: auto

experiment:
  name: 2026-03-27-samudra_llc:Agulhas_patch:TEST:pred_resid=true #,noise_injection_test
  data_root: /orcd/data/abodner/
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online #disabled
    project: default
  prognostic_vars_key: all #single1
  boundary_vars_key: all

data: !include ../data/llc.yaml
model: !include model.yaml