# yaml-language-server: $schema=../schemas/TrainConfig.json

debug: false
disk_mode: true
pin_mem: true
save_freq: 1
epochs: 24
batch_size: 1
learning_rate: 0.0006
gradient_accumulation_steps: 4
scheduler: { type: cosine }
lr_multipliers: [1.0]
lr_multiplier_transition: []
loss:
  type: gradient
  metric: mae
  alpha: 0.1
finetune: false
#resume_ckpt_path: .LOCAL/2026-04-03-CONT:[increase-step-test-suite]-WITH_temporal_stride=6,steps=4,2011-09-14-2012-01-01-RESUME/saved_nets/ckpt.pt
reset_optimizer_on_resume: false
reset_scheduler_on_resume: false
inference_epochs: []
data_percent: 1.0
train_time:
  start: "2011-09-13"
  end: "2012-09-13"
val_time:
  start: "2012-09-14" # "2011-09-15"
  end: "2012-10-01" # "2011-09-16"
inference_times:
  - start: "2012-10-01"
    end: "2012-10-04"
data_stride: [6]
temporal_stride: 6
steps: [2]
step_transition: []
temporal_stride_transition: []
preemptible: false

backend: auto

experiment:
  name: 2026-05-21:samudra_llc:long_curriculum_strides=3_CONT
  data_root: /orcd/data/abodner/
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: online #disabled
    project: default
  prognostic_vars_key: all #single1
  boundary_vars_key: all

data: !include ../data/llc.yaml
model: !include model.yaml
