name: Start AWS Runner

on:
  workflow_call:
    inputs:
      aws_image_id:
        description: "AWS AMI ID to use"
        required: false
        type: string
        default: "ami-0365bff494b18bf93" # Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.7 (Ubuntu 22.04) in oa-ci-dev
      aws_instance_type:
        description: "AWS instance type"
        required: false
        type: string
        default: "g6.xlarge"
      aws_home_dir:
        description: "Home directory on the AWS instance"
        required: false
        type: string
        default: "/home/ubuntu"
      aws_root_device_size:
        description: "Root device size in GB"
        required: false
        type: number
        default: 200
    outputs:
      mapping:
        description: "Instance mapping for stopping later"
        value: ${{ jobs.start-aws-runner.outputs.mapping }}
      instances:
        description: "Instance IDs"
        value: ${{ jobs.start-aws-runner.outputs.instances }}
    secrets:
      AWS_ROLE:
        required: true
      GH_SA_TOKEN:
        required: true

permissions:
  id-token: write # This is required for interacting with AWS via OIDC

jobs:
  start-aws-runner:
    runs-on: ubuntu-latest
    outputs:
      mapping: ${{ steps.aws-start.outputs.mapping }}
      instances: ${{ steps.aws-start.outputs.instances }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: github-actions-session
          aws-region: us-east-1

      - name: Create cloud runner
        id: aws-start
        uses: omsf/start-aws-gha-runner@v1.0.0
        with:
          aws_image_id: ${{ inputs.aws_image_id }}
          aws_instance_type: ${{ inputs.aws_instance_type }}
          aws_home_dir: ${{ inputs.aws_home_dir }}
          aws_root_device_size: ${{ inputs.aws_root_device_size }}
        env:
          GH_PAT: ${{ secrets.GH_SA_TOKEN }}
