# Performance benchmarks with pytest
# Based on this example: https://github.com/benchmark-action/github-action-benchmark/tree/master/examples/pytest
name: Benchmark

# Do not run this workflow on pull request since this workflow has permission to modify contents.
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write # Allow updating content on GitHub pages
  deployments: write # Allow to deploy to GitHub pages

jobs:
  start-aws-runner:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      mapping: ${{ steps.aws-start.outputs.mapping }}
      instances: ${{ steps.aws-start.outputs.instances }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: github-actions-session
          aws-region: us-east-1

      - name: Create cloud runner
        id: aws-start
        uses: omsf/start-aws-gha-runner@v1.0.0
        with:
          aws_image_id: ami-00096836009b16a22 # Deep Learning OSS Nvidia Driver AMI GPU PyTorch
          aws_instance_type: g6.xlarge
          aws_home_dir: /home/ubuntu
        env:
          GH_PAT: ${{ secrets.GH_SA_TOKEN }}

  test:
    needs: start-aws-runner
    runs-on: ${{ fromJSON(needs.start-aws-runner.outputs.instances) }}

    env:
      # see note about machine image above
      CUDA_VERSION: 12.1
    steps:
      - name: Check out code
        uses: actions/checkout@v2

        # Invalidate the data cache every time the data source changes.
        # If an exact cache isn't found, fall back to previous cache.
      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: .data_cache/
          key: ${{ runner.os }}-test-data-${{ hashFiles('tests/conftest.py', 'configs/*.test.yaml') }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Run CPU benchmarks
        run: uv run --locked pytest -m "not cuda" --benchmark-only --benchmark-json output-cpu.json

      - name: Run GPU benchmarks
        run: uv run --locked pytest -m "cuda" --benchmark-only --benchmark-json output-gpu.json

      # Avoid issues checking out the gh-pages branch (eg uv.lock updated)
      - name: Stash
        run: git stash

      # gh-pages branch is automatically updated with extracted benchmark data.
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: "pytest"
          output-file-path: output-cpu.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@alxmrs,@jder"

      # gh-pages branch is automatically updated with extracted benchmark data.
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark (GPU)
          tool: "pytest"
          output-file-path: output-gpu.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@alxmrs,@jder"

  stop-aws-runner:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
    needs:
      - start-aws-runner
      - test
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Stop instances
        uses: omsf/stop-aws-gha-runner@v1.0.0
        with:
          instance_mapping: ${{ needs.start-aws-runner.outputs.mapping }}
        env:
          GH_PAT: ${{ secrets.GH_SA_TOKEN }}