name: Test GPU
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  start-aws-runner:
    runs-on: ubuntu-latest
    outputs:
      mapping: ${{ steps.aws-start.outputs.mapping }}
      instances: ${{ steps.aws-start.outputs.instances }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: github-actions-session
          aws-region: us-east-1

      - name: Create cloud runner
        id: aws-start
        uses: mihasya/start-aws-gha-runner@fix-worker-lookup
        with:
          aws_image_id: ami-00096836009b16a22 # Deep Learning OSS Nvidia Driver AMI GPU PyTorch
          aws_instance_type: g6.xlarge
          aws_home_dir: /home/ubuntu

  run-tests:
    needs: start-aws-runner
    runs-on: ${{ fromJSON(needs.start-aws-runner.outputs.instances) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

        # Invalidate the data cache every time the data source changes.
        # If an exact cache isn't found, fall back to previous cache.
      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: .data_cache/
          key: ${{ runner.os }}-test-data-${{ hashFiles('tests/conftest.py', 'configs/*.test.yaml') }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --locked --dev --all-extras

      - name: Run pytest
        run: uv run --locked pytest -n 2 -v -m "not manual and cuda"

  stop-aws-runner:
    runs-on: ubuntu-latest
    needs:
      - start-aws-runner
      - run-tests
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Stop instances
        uses: omsf/stop-aws-gha-runner@v1.0.0
        with:
          instance_mapping: ${{ needs.start-aws-runner.outputs.mapping }}