name: Test GPU
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # This is required for interacting with AWS via OIDC
  contents: read # This is required for actions/checkout
jobs:
  start-aws-runner:
    uses: ./.github/workflows/aws-runner-start.yml
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      GH_SA_TOKEN: ${{ secrets.GH_SA_TOKEN }}

  run-tests:
    needs: start-aws-runner
    runs-on: ${{ fromJSON(needs.start-aws-runner.outputs.instances) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

        # Invalidate the data cache every time the data source changes.
        # If an exact cache isn't found, fall back to previous cache.
      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: .data_cache/
          key: ${{ runner.os }}-test-data-${{ hashFiles('tests/conftest.py', 'configs/*.test.yaml') }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv sync --locked --dev --all-extras

      - name: Run pytest
        run: uv run --locked pytest -n 2 -v -m "not manual and cuda"

  stop-aws-runner:
    uses: ./.github/workflows/aws-runner-stop.yml
    needs:
      - start-aws-runner
      - run-tests
    if: ${{ always() }}
    with:
      instance_mapping: ${{ needs.start-aws-runner.outputs.mapping }}
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      GH_SA_TOKEN: ${{ secrets.GH_SA_TOKEN }}
