name: Test GPU
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for interacting with AWS via OIDC
  contents: read # Required for actions/checkout (normally set by default, but must explicitly specify when defining a custom `permissions` block.

jobs:
  ec2:
    uses: Open-Athena/ec2-gha/.github/workflows/runner.yml@v2
    secrets:
      GH_SA_TOKEN: ${{ secrets.GH_SA_TOKEN }}
  run-tests:
    needs: ec2
    runs-on: ${{ needs.ec2.outputs.id }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

        # Invalidate the data cache every time the data source changes.
        # If an exact cache isn't found, fall back to previous cache.
      - name: Cache test data
        uses: actions/cache@v3
        with:
          path: .data_cache/
          key: ${{ runner.os }}-test-data-${{ hashFiles('tests/conftest.py', 'configs/*.test.yaml') }}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync --locked --dev --all-extras

      - name: Run pytest
        run: uv run --locked pytest -n 2 -v -m "not manual and cuda"
